# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import beverage_service_pb2 as beverage__service__pb2


class prepare_beverage_serviceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.prepare_beverage = channel.unary_unary(
                '/swdv.beverage_service.prepare_beverage_service/prepare_beverage',
                request_serializer=beverage__service__pb2.prepare_beverage_request.SerializeToString,
                response_deserializer=beverage__service__pb2.prepare_beverage_response.FromString,
                )


class prepare_beverage_serviceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def prepare_beverage(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_prepare_beverage_serviceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'prepare_beverage': grpc.unary_unary_rpc_method_handler(
                    servicer.prepare_beverage,
                    request_deserializer=beverage__service__pb2.prepare_beverage_request.FromString,
                    response_serializer=beverage__service__pb2.prepare_beverage_response.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'swdv.beverage_service.prepare_beverage_service', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class prepare_beverage_service(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def prepare_beverage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/swdv.beverage_service.prepare_beverage_service/prepare_beverage',
            beverage__service__pb2.prepare_beverage_request.SerializeToString,
            beverage__service__pb2.prepare_beverage_response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)


class get_preparation_status_serviceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.get_preparation_status = channel.unary_unary(
                '/swdv.beverage_service.get_preparation_status_service/get_preparation_status',
                request_serializer=beverage__service__pb2.get_preparation_status_request.SerializeToString,
                response_deserializer=beverage__service__pb2.get_preparation_status_response.FromString,
                )


class get_preparation_status_serviceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def get_preparation_status(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_get_preparation_status_serviceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'get_preparation_status': grpc.unary_unary_rpc_method_handler(
                    servicer.get_preparation_status,
                    request_deserializer=beverage__service__pb2.get_preparation_status_request.FromString,
                    response_serializer=beverage__service__pb2.get_preparation_status_response.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'swdv.beverage_service.get_preparation_status_service', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class get_preparation_status_service(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def get_preparation_status(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/swdv.beverage_service.get_preparation_status_service/get_preparation_status',
            beverage__service__pb2.get_preparation_status_request.SerializeToString,
            beverage__service__pb2.get_preparation_status_response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)


class cancel_preparation_serviceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.cancel_preparation = channel.unary_unary(
                '/swdv.beverage_service.cancel_preparation_service/cancel_preparation',
                request_serializer=beverage__service__pb2.cancel_preparation_request.SerializeToString,
                response_deserializer=beverage__service__pb2.cancel_preparation_response.FromString,
                )


class cancel_preparation_serviceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def cancel_preparation(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_cancel_preparation_serviceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'cancel_preparation': grpc.unary_unary_rpc_method_handler(
                    servicer.cancel_preparation,
                    request_deserializer=beverage__service__pb2.cancel_preparation_request.FromString,
                    response_serializer=beverage__service__pb2.cancel_preparation_response.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'swdv.beverage_service.cancel_preparation_service', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class cancel_preparation_service(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def cancel_preparation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/swdv.beverage_service.cancel_preparation_service/cancel_preparation',
            beverage__service__pb2.cancel_preparation_request.SerializeToString,
            beverage__service__pb2.cancel_preparation_response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)


class get_capabilities_serviceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.get_capabilities = channel.unary_unary(
                '/swdv.beverage_service.get_capabilities_service/get_capabilities',
                request_serializer=beverage__service__pb2.get_capabilities_request.SerializeToString,
                response_deserializer=beverage__service__pb2.get_capabilities_response.FromString,
                )


class get_capabilities_serviceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def get_capabilities(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_get_capabilities_serviceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'get_capabilities': grpc.unary_unary_rpc_method_handler(
                    servicer.get_capabilities,
                    request_deserializer=beverage__service__pb2.get_capabilities_request.FromString,
                    response_serializer=beverage__service__pb2.get_capabilities_response.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'swdv.beverage_service.get_capabilities_service', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class get_capabilities_service(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def get_capabilities(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/swdv.beverage_service.get_capabilities_service/get_capabilities',
            beverage__service__pb2.get_capabilities_request.SerializeToString,
            beverage__service__pb2.get_capabilities_response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
