# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import defrost_service_pb2 as defrost__service__pb2


class start_defrost_serviceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.start_defrost = channel.unary_unary(
                '/swdv.defrost_service.start_defrost_service/start_defrost',
                request_serializer=defrost__service__pb2.start_defrost_request.SerializeToString,
                response_deserializer=defrost__service__pb2.start_defrost_response.FromString,
                )


class start_defrost_serviceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def start_defrost(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_start_defrost_serviceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'start_defrost': grpc.unary_unary_rpc_method_handler(
                    servicer.start_defrost,
                    request_deserializer=defrost__service__pb2.start_defrost_request.FromString,
                    response_serializer=defrost__service__pb2.start_defrost_response.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'swdv.defrost_service.start_defrost_service', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class start_defrost_service(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def start_defrost(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/swdv.defrost_service.start_defrost_service/start_defrost',
            defrost__service__pb2.start_defrost_request.SerializeToString,
            defrost__service__pb2.start_defrost_response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)


class stop_defrost_serviceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.stop_defrost = channel.unary_unary(
                '/swdv.defrost_service.stop_defrost_service/stop_defrost',
                request_serializer=defrost__service__pb2.stop_defrost_request.SerializeToString,
                response_deserializer=defrost__service__pb2.stop_defrost_response.FromString,
                )


class stop_defrost_serviceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def stop_defrost(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_stop_defrost_serviceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'stop_defrost': grpc.unary_unary_rpc_method_handler(
                    servicer.stop_defrost,
                    request_deserializer=defrost__service__pb2.stop_defrost_request.FromString,
                    response_serializer=defrost__service__pb2.stop_defrost_response.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'swdv.defrost_service.stop_defrost_service', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class stop_defrost_service(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def stop_defrost(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/swdv.defrost_service.stop_defrost_service/stop_defrost',
            defrost__service__pb2.stop_defrost_request.SerializeToString,
            defrost__service__pb2.stop_defrost_response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)


class get_visibility_status_serviceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.get_visibility_status = channel.unary_unary(
                '/swdv.defrost_service.get_visibility_status_service/get_visibility_status',
                request_serializer=defrost__service__pb2.get_visibility_status_request.SerializeToString,
                response_deserializer=defrost__service__pb2.get_visibility_status_response.FromString,
                )


class get_visibility_status_serviceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def get_visibility_status(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_get_visibility_status_serviceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'get_visibility_status': grpc.unary_unary_rpc_method_handler(
                    servicer.get_visibility_status,
                    request_deserializer=defrost__service__pb2.get_visibility_status_request.FromString,
                    response_serializer=defrost__service__pb2.get_visibility_status_response.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'swdv.defrost_service.get_visibility_status_service', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class get_visibility_status_service(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def get_visibility_status(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/swdv.defrost_service.get_visibility_status_service/get_visibility_status',
            defrost__service__pb2.get_visibility_status_request.SerializeToString,
            defrost__service__pb2.get_visibility_status_response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)


class quick_clear_windshield_serviceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.quick_clear_windshield = channel.unary_unary(
                '/swdv.defrost_service.quick_clear_windshield_service/quick_clear_windshield',
                request_serializer=defrost__service__pb2.quick_clear_windshield_request.SerializeToString,
                response_deserializer=defrost__service__pb2.quick_clear_windshield_response.FromString,
                )


class quick_clear_windshield_serviceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def quick_clear_windshield(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_quick_clear_windshield_serviceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'quick_clear_windshield': grpc.unary_unary_rpc_method_handler(
                    servicer.quick_clear_windshield,
                    request_deserializer=defrost__service__pb2.quick_clear_windshield_request.FromString,
                    response_serializer=defrost__service__pb2.quick_clear_windshield_response.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'swdv.defrost_service.quick_clear_windshield_service', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class quick_clear_windshield_service(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def quick_clear_windshield(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/swdv.defrost_service.quick_clear_windshield_service/quick_clear_windshield',
            defrost__service__pb2.quick_clear_windshield_request.SerializeToString,
            defrost__service__pb2.quick_clear_windshield_response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
