# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import departure_orchestration_service_pb2 as departure__orchestration__service__pb2


class schedule_departure_serviceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.schedule_departure = channel.unary_unary(
                '/swdv.departure_orchestration_service.schedule_departure_service/schedule_departure',
                request_serializer=departure__orchestration__service__pb2.schedule_departure_request.SerializeToString,
                response_deserializer=departure__orchestration__service__pb2.schedule_departure_response.FromString,
                )


class schedule_departure_serviceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def schedule_departure(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_schedule_departure_serviceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'schedule_departure': grpc.unary_unary_rpc_method_handler(
                    servicer.schedule_departure,
                    request_deserializer=departure__orchestration__service__pb2.schedule_departure_request.FromString,
                    response_serializer=departure__orchestration__service__pb2.schedule_departure_response.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'swdv.departure_orchestration_service.schedule_departure_service', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class schedule_departure_service(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def schedule_departure(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/swdv.departure_orchestration_service.schedule_departure_service/schedule_departure',
            departure__orchestration__service__pb2.schedule_departure_request.SerializeToString,
            departure__orchestration__service__pb2.schedule_departure_response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)


class get_schedule_status_serviceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.get_schedule_status = channel.unary_unary(
                '/swdv.departure_orchestration_service.get_schedule_status_service/get_schedule_status',
                request_serializer=departure__orchestration__service__pb2.get_schedule_status_request.SerializeToString,
                response_deserializer=departure__orchestration__service__pb2.get_schedule_status_response.FromString,
                )


class get_schedule_status_serviceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def get_schedule_status(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_get_schedule_status_serviceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'get_schedule_status': grpc.unary_unary_rpc_method_handler(
                    servicer.get_schedule_status,
                    request_deserializer=departure__orchestration__service__pb2.get_schedule_status_request.FromString,
                    response_serializer=departure__orchestration__service__pb2.get_schedule_status_response.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'swdv.departure_orchestration_service.get_schedule_status_service', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class get_schedule_status_service(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def get_schedule_status(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/swdv.departure_orchestration_service.get_schedule_status_service/get_schedule_status',
            departure__orchestration__service__pb2.get_schedule_status_request.SerializeToString,
            departure__orchestration__service__pb2.get_schedule_status_response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)


class cancel_schedule_serviceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.cancel_schedule = channel.unary_unary(
                '/swdv.departure_orchestration_service.cancel_schedule_service/cancel_schedule',
                request_serializer=departure__orchestration__service__pb2.cancel_schedule_request.SerializeToString,
                response_deserializer=departure__orchestration__service__pb2.cancel_schedule_response.FromString,
                )


class cancel_schedule_serviceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def cancel_schedule(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_cancel_schedule_serviceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'cancel_schedule': grpc.unary_unary_rpc_method_handler(
                    servicer.cancel_schedule,
                    request_deserializer=departure__orchestration__service__pb2.cancel_schedule_request.FromString,
                    response_serializer=departure__orchestration__service__pb2.cancel_schedule_response.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'swdv.departure_orchestration_service.cancel_schedule_service', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class cancel_schedule_service(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def cancel_schedule(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/swdv.departure_orchestration_service.cancel_schedule_service/cancel_schedule',
            departure__orchestration__service__pb2.cancel_schedule_request.SerializeToString,
            departure__orchestration__service__pb2.cancel_schedule_response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)


class modify_schedule_serviceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.modify_schedule = channel.unary_unary(
                '/swdv.departure_orchestration_service.modify_schedule_service/modify_schedule',
                request_serializer=departure__orchestration__service__pb2.modify_schedule_request.SerializeToString,
                response_deserializer=departure__orchestration__service__pb2.modify_schedule_response.FromString,
                )


class modify_schedule_serviceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def modify_schedule(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_modify_schedule_serviceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'modify_schedule': grpc.unary_unary_rpc_method_handler(
                    servicer.modify_schedule,
                    request_deserializer=departure__orchestration__service__pb2.modify_schedule_request.FromString,
                    response_serializer=departure__orchestration__service__pb2.modify_schedule_response.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'swdv.departure_orchestration_service.modify_schedule_service', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class modify_schedule_service(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def modify_schedule(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/swdv.departure_orchestration_service.modify_schedule_service/modify_schedule',
            departure__orchestration__service__pb2.modify_schedule_request.SerializeToString,
            departure__orchestration__service__pb2.modify_schedule_response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)


class get_active_schedules_serviceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.get_active_schedules = channel.unary_unary(
                '/swdv.departure_orchestration_service.get_active_schedules_service/get_active_schedules',
                request_serializer=departure__orchestration__service__pb2.get_active_schedules_request.SerializeToString,
                response_deserializer=departure__orchestration__service__pb2.get_active_schedules_response.FromString,
                )


class get_active_schedules_serviceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def get_active_schedules(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_get_active_schedules_serviceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'get_active_schedules': grpc.unary_unary_rpc_method_handler(
                    servicer.get_active_schedules,
                    request_deserializer=departure__orchestration__service__pb2.get_active_schedules_request.FromString,
                    response_serializer=departure__orchestration__service__pb2.get_active_schedules_response.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'swdv.departure_orchestration_service.get_active_schedules_service', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class get_active_schedules_service(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def get_active_schedules(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/swdv.departure_orchestration_service.get_active_schedules_service/get_active_schedules',
            departure__orchestration__service__pb2.get_active_schedules_request.SerializeToString,
            departure__orchestration__service__pb2.get_active_schedules_response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
