# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import service_discovery_service_pb2 as service__discovery__service__pb2


class register_service_serviceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.register_service = channel.unary_unary(
                '/swdv.service_discovery.register_service_service/register_service',
                request_serializer=service__discovery__service__pb2.register_service_request.SerializeToString,
                response_deserializer=service__discovery__service__pb2.register_service_response.FromString,
                )


class register_service_serviceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def register_service(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_register_service_serviceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'register_service': grpc.unary_unary_rpc_method_handler(
                    servicer.register_service,
                    request_deserializer=service__discovery__service__pb2.register_service_request.FromString,
                    response_serializer=service__discovery__service__pb2.register_service_response.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'swdv.service_discovery.register_service_service', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class register_service_service(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def register_service(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/swdv.service_discovery.register_service_service/register_service',
            service__discovery__service__pb2.register_service_request.SerializeToString,
            service__discovery__service__pb2.register_service_response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)


class unregister_service_serviceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.unregister_service = channel.unary_unary(
                '/swdv.service_discovery.unregister_service_service/unregister_service',
                request_serializer=service__discovery__service__pb2.unregister_service_request.SerializeToString,
                response_deserializer=service__discovery__service__pb2.unregister_service_response.FromString,
                )


class unregister_service_serviceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def unregister_service(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_unregister_service_serviceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'unregister_service': grpc.unary_unary_rpc_method_handler(
                    servicer.unregister_service,
                    request_deserializer=service__discovery__service__pb2.unregister_service_request.FromString,
                    response_serializer=service__discovery__service__pb2.unregister_service_response.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'swdv.service_discovery.unregister_service_service', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class unregister_service_service(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def unregister_service(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/swdv.service_discovery.unregister_service_service/unregister_service',
            service__discovery__service__pb2.unregister_service_request.SerializeToString,
            service__discovery__service__pb2.unregister_service_response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)


class get_service_serviceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.get_service = channel.unary_unary(
                '/swdv.service_discovery.get_service_service/get_service',
                request_serializer=service__discovery__service__pb2.get_service_request.SerializeToString,
                response_deserializer=service__discovery__service__pb2.get_service_response.FromString,
                )


class get_service_serviceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def get_service(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_get_service_serviceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'get_service': grpc.unary_unary_rpc_method_handler(
                    servicer.get_service,
                    request_deserializer=service__discovery__service__pb2.get_service_request.FromString,
                    response_serializer=service__discovery__service__pb2.get_service_response.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'swdv.service_discovery.get_service_service', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class get_service_service(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def get_service(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/swdv.service_discovery.get_service_service/get_service',
            service__discovery__service__pb2.get_service_request.SerializeToString,
            service__discovery__service__pb2.get_service_response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)


class query_services_serviceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.query_services = channel.unary_unary(
                '/swdv.service_discovery.query_services_service/query_services',
                request_serializer=service__discovery__service__pb2.query_services_request.SerializeToString,
                response_deserializer=service__discovery__service__pb2.query_services_response.FromString,
                )


class query_services_serviceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def query_services(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_query_services_serviceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'query_services': grpc.unary_unary_rpc_method_handler(
                    servicer.query_services,
                    request_deserializer=service__discovery__service__pb2.query_services_request.FromString,
                    response_serializer=service__discovery__service__pb2.query_services_response.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'swdv.service_discovery.query_services_service', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class query_services_service(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def query_services(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/swdv.service_discovery.query_services_service/query_services',
            service__discovery__service__pb2.query_services_request.SerializeToString,
            service__discovery__service__pb2.query_services_response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)


class validate_method_call_serviceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.validate_method_call = channel.unary_unary(
                '/swdv.service_discovery.validate_method_call_service/validate_method_call',
                request_serializer=service__discovery__service__pb2.validate_method_call_request.SerializeToString,
                response_deserializer=service__discovery__service__pb2.validate_method_call_response.FromString,
                )


class validate_method_call_serviceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def validate_method_call(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_validate_method_call_serviceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'validate_method_call': grpc.unary_unary_rpc_method_handler(
                    servicer.validate_method_call,
                    request_deserializer=service__discovery__service__pb2.validate_method_call_request.FromString,
                    response_serializer=service__discovery__service__pb2.validate_method_call_response.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'swdv.service_discovery.validate_method_call_service', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class validate_method_call_service(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def validate_method_call(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/swdv.service_discovery.validate_method_call_service/validate_method_call',
            service__discovery__service__pb2.validate_method_call_request.SerializeToString,
            service__discovery__service__pb2.validate_method_call_response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)


class get_method_schema_serviceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.get_method_schema = channel.unary_unary(
                '/swdv.service_discovery.get_method_schema_service/get_method_schema',
                request_serializer=service__discovery__service__pb2.get_method_schema_request.SerializeToString,
                response_deserializer=service__discovery__service__pb2.get_method_schema_response.FromString,
                )


class get_method_schema_serviceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def get_method_schema(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_get_method_schema_serviceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'get_method_schema': grpc.unary_unary_rpc_method_handler(
                    servicer.get_method_schema,
                    request_deserializer=service__discovery__service__pb2.get_method_schema_request.FromString,
                    response_serializer=service__discovery__service__pb2.get_method_schema_response.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'swdv.service_discovery.get_method_schema_service', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class get_method_schema_service(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def get_method_schema(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/swdv.service_discovery.get_method_schema_service/get_method_schema',
            service__discovery__service__pb2.get_method_schema_request.SerializeToString,
            service__discovery__service__pb2.get_method_schema_response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)


class heartbeat_serviceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.heartbeat = channel.unary_unary(
                '/swdv.service_discovery.heartbeat_service/heartbeat',
                request_serializer=service__discovery__service__pb2.heartbeat_request.SerializeToString,
                response_deserializer=service__discovery__service__pb2.heartbeat_response.FromString,
                )


class heartbeat_serviceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def heartbeat(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_heartbeat_serviceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'heartbeat': grpc.unary_unary_rpc_method_handler(
                    servicer.heartbeat,
                    request_deserializer=service__discovery__service__pb2.heartbeat_request.FromString,
                    response_serializer=service__discovery__service__pb2.heartbeat_response.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'swdv.service_discovery.heartbeat_service', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class heartbeat_service(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def heartbeat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/swdv.service_discovery.heartbeat_service/heartbeat',
            service__discovery__service__pb2.heartbeat_request.SerializeToString,
            service__discovery__service__pb2.heartbeat_response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)


class get_service_hashes_serviceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.get_service_hashes = channel.unary_unary(
                '/swdv.service_discovery.get_service_hashes_service/get_service_hashes',
                request_serializer=service__discovery__service__pb2.get_service_hashes_request.SerializeToString,
                response_deserializer=service__discovery__service__pb2.get_service_hashes_response.FromString,
                )


class get_service_hashes_serviceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def get_service_hashes(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_get_service_hashes_serviceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'get_service_hashes': grpc.unary_unary_rpc_method_handler(
                    servicer.get_service_hashes,
                    request_deserializer=service__discovery__service__pb2.get_service_hashes_request.FromString,
                    response_serializer=service__discovery__service__pb2.get_service_hashes_response.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'swdv.service_discovery.get_service_hashes_service', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class get_service_hashes_service(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def get_service_hashes(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/swdv.service_discovery.get_service_hashes_service/get_service_hashes',
            service__discovery__service__pb2.get_service_hashes_request.SerializeToString,
            service__discovery__service__pb2.get_service_hashes_response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)


class get_schemas_by_hash_serviceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.get_schemas_by_hash = channel.unary_unary(
                '/swdv.service_discovery.get_schemas_by_hash_service/get_schemas_by_hash',
                request_serializer=service__discovery__service__pb2.get_schemas_by_hash_request.SerializeToString,
                response_deserializer=service__discovery__service__pb2.get_schemas_by_hash_response.FromString,
                )


class get_schemas_by_hash_serviceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def get_schemas_by_hash(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_get_schemas_by_hash_serviceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'get_schemas_by_hash': grpc.unary_unary_rpc_method_handler(
                    servicer.get_schemas_by_hash,
                    request_deserializer=service__discovery__service__pb2.get_schemas_by_hash_request.FromString,
                    response_serializer=service__discovery__service__pb2.get_schemas_by_hash_response.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'swdv.service_discovery.get_schemas_by_hash_service', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class get_schemas_by_hash_service(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def get_schemas_by_hash(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/swdv.service_discovery.get_schemas_by_hash_service/get_schemas_by_hash',
            service__discovery__service__pb2.get_schemas_by_hash_request.SerializeToString,
            service__discovery__service__pb2.get_schemas_by_hash_response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
