# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import settings_service_pb2 as settings__service__pb2


class get_presets_serviceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.get_presets = channel.unary_unary(
                '/swdv.settings_service.get_presets_service/get_presets',
                request_serializer=settings__service__pb2.get_presets_request.SerializeToString,
                response_deserializer=settings__service__pb2.get_presets_response.FromString,
                )


class get_presets_serviceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def get_presets(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_get_presets_serviceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'get_presets': grpc.unary_unary_rpc_method_handler(
                    servicer.get_presets,
                    request_deserializer=settings__service__pb2.get_presets_request.FromString,
                    response_serializer=settings__service__pb2.get_presets_response.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'swdv.settings_service.get_presets_service', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class get_presets_service(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def get_presets(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/swdv.settings_service.get_presets_service/get_presets',
            settings__service__pb2.get_presets_request.SerializeToString,
            settings__service__pb2.get_presets_response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)


class get_preset_serviceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.get_preset = channel.unary_unary(
                '/swdv.settings_service.get_preset_service/get_preset',
                request_serializer=settings__service__pb2.get_preset_request.SerializeToString,
                response_deserializer=settings__service__pb2.get_preset_response.FromString,
                )


class get_preset_serviceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def get_preset(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_get_preset_serviceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'get_preset': grpc.unary_unary_rpc_method_handler(
                    servicer.get_preset,
                    request_deserializer=settings__service__pb2.get_preset_request.FromString,
                    response_serializer=settings__service__pb2.get_preset_response.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'swdv.settings_service.get_preset_service', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class get_preset_service(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def get_preset(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/swdv.settings_service.get_preset_service/get_preset',
            settings__service__pb2.get_preset_request.SerializeToString,
            settings__service__pb2.get_preset_response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)


class create_preset_serviceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.create_preset = channel.unary_unary(
                '/swdv.settings_service.create_preset_service/create_preset',
                request_serializer=settings__service__pb2.create_preset_request.SerializeToString,
                response_deserializer=settings__service__pb2.create_preset_response.FromString,
                )


class create_preset_serviceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def create_preset(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_create_preset_serviceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'create_preset': grpc.unary_unary_rpc_method_handler(
                    servicer.create_preset,
                    request_deserializer=settings__service__pb2.create_preset_request.FromString,
                    response_serializer=settings__service__pb2.create_preset_response.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'swdv.settings_service.create_preset_service', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class create_preset_service(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def create_preset(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/swdv.settings_service.create_preset_service/create_preset',
            settings__service__pb2.create_preset_request.SerializeToString,
            settings__service__pb2.create_preset_response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)


class update_preset_serviceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.update_preset = channel.unary_unary(
                '/swdv.settings_service.update_preset_service/update_preset',
                request_serializer=settings__service__pb2.update_preset_request.SerializeToString,
                response_deserializer=settings__service__pb2.update_preset_response.FromString,
                )


class update_preset_serviceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def update_preset(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_update_preset_serviceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'update_preset': grpc.unary_unary_rpc_method_handler(
                    servicer.update_preset,
                    request_deserializer=settings__service__pb2.update_preset_request.FromString,
                    response_serializer=settings__service__pb2.update_preset_response.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'swdv.settings_service.update_preset_service', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class update_preset_service(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def update_preset(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/swdv.settings_service.update_preset_service/update_preset',
            settings__service__pb2.update_preset_request.SerializeToString,
            settings__service__pb2.update_preset_response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)


class delete_preset_serviceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.delete_preset = channel.unary_unary(
                '/swdv.settings_service.delete_preset_service/delete_preset',
                request_serializer=settings__service__pb2.delete_preset_request.SerializeToString,
                response_deserializer=settings__service__pb2.delete_preset_response.FromString,
                )


class delete_preset_serviceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def delete_preset(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_delete_preset_serviceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'delete_preset': grpc.unary_unary_rpc_method_handler(
                    servicer.delete_preset,
                    request_deserializer=settings__service__pb2.delete_preset_request.FromString,
                    response_serializer=settings__service__pb2.delete_preset_response.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'swdv.settings_service.delete_preset_service', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class delete_preset_service(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def delete_preset(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/swdv.settings_service.delete_preset_service/delete_preset',
            settings__service__pb2.delete_preset_request.SerializeToString,
            settings__service__pb2.delete_preset_response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)


class apply_preset_serviceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.apply_preset = channel.unary_unary(
                '/swdv.settings_service.apply_preset_service/apply_preset',
                request_serializer=settings__service__pb2.apply_preset_request.SerializeToString,
                response_deserializer=settings__service__pb2.apply_preset_response.FromString,
                )


class apply_preset_serviceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def apply_preset(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_apply_preset_serviceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'apply_preset': grpc.unary_unary_rpc_method_handler(
                    servicer.apply_preset,
                    request_deserializer=settings__service__pb2.apply_preset_request.FromString,
                    response_serializer=settings__service__pb2.apply_preset_response.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'swdv.settings_service.apply_preset_service', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class apply_preset_service(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def apply_preset(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/swdv.settings_service.apply_preset_service/apply_preset',
            settings__service__pb2.apply_preset_request.SerializeToString,
            settings__service__pb2.apply_preset_response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)


class export_presets_serviceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.export_presets = channel.unary_unary(
                '/swdv.settings_service.export_presets_service/export_presets',
                request_serializer=settings__service__pb2.export_presets_request.SerializeToString,
                response_deserializer=settings__service__pb2.export_presets_response.FromString,
                )


class export_presets_serviceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def export_presets(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_export_presets_serviceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'export_presets': grpc.unary_unary_rpc_method_handler(
                    servicer.export_presets,
                    request_deserializer=settings__service__pb2.export_presets_request.FromString,
                    response_serializer=settings__service__pb2.export_presets_response.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'swdv.settings_service.export_presets_service', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class export_presets_service(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def export_presets(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/swdv.settings_service.export_presets_service/export_presets',
            settings__service__pb2.export_presets_request.SerializeToString,
            settings__service__pb2.export_presets_response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)


class import_presets_serviceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.import_presets = channel.unary_unary(
                '/swdv.settings_service.import_presets_service/import_presets',
                request_serializer=settings__service__pb2.import_presets_request.SerializeToString,
                response_deserializer=settings__service__pb2.import_presets_response.FromString,
                )


class import_presets_serviceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def import_presets(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_import_presets_serviceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'import_presets': grpc.unary_unary_rpc_method_handler(
                    servicer.import_presets,
                    request_deserializer=settings__service__pb2.import_presets_request.FromString,
                    response_serializer=settings__service__pb2.import_presets_response.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'swdv.settings_service.import_presets_service', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class import_presets_service(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def import_presets(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/swdv.settings_service.import_presets_service/import_presets',
            settings__service__pb2.import_presets_request.SerializeToString,
            settings__service__pb2.import_presets_response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)


class validate_preset_serviceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.validate_preset = channel.unary_unary(
                '/swdv.settings_service.validate_preset_service/validate_preset',
                request_serializer=settings__service__pb2.validate_preset_request.SerializeToString,
                response_deserializer=settings__service__pb2.validate_preset_response.FromString,
                )


class validate_preset_serviceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def validate_preset(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_validate_preset_serviceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'validate_preset': grpc.unary_unary_rpc_method_handler(
                    servicer.validate_preset,
                    request_deserializer=settings__service__pb2.validate_preset_request.FromString,
                    response_serializer=settings__service__pb2.validate_preset_response.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'swdv.settings_service.validate_preset_service', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class validate_preset_service(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def validate_preset(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/swdv.settings_service.validate_preset_service/validate_preset',
            settings__service__pb2.validate_preset_request.SerializeToString,
            settings__service__pb2.validate_preset_response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
