# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import cloud_scheduler_sync_bridge_pb2 as cloud__scheduler__sync__bridge__pb2


class get_stats_serviceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.get_stats = channel.unary_unary(
                '/swdv.cloud_scheduler_sync_bridge.get_stats_service/get_stats',
                request_serializer=cloud__scheduler__sync__bridge__pb2.get_stats_request.SerializeToString,
                response_deserializer=cloud__scheduler__sync__bridge__pb2.get_stats_response.FromString,
                )


class get_stats_serviceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def get_stats(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_get_stats_serviceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'get_stats': grpc.unary_unary_rpc_method_handler(
                    servicer.get_stats,
                    request_deserializer=cloud__scheduler__sync__bridge__pb2.get_stats_request.FromString,
                    response_serializer=cloud__scheduler__sync__bridge__pb2.get_stats_response.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'swdv.cloud_scheduler_sync_bridge.get_stats_service', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class get_stats_service(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def get_stats(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/swdv.cloud_scheduler_sync_bridge.get_stats_service/get_stats',
            cloud__scheduler__sync__bridge__pb2.get_stats_request.SerializeToString,
            cloud__scheduler__sync__bridge__pb2.get_stats_response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)


class get_health_serviceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.get_health = channel.unary_unary(
                '/swdv.cloud_scheduler_sync_bridge.get_health_service/get_health',
                request_serializer=cloud__scheduler__sync__bridge__pb2.get_health_request.SerializeToString,
                response_deserializer=cloud__scheduler__sync__bridge__pb2.get_health_response.FromString,
                )


class get_health_serviceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def get_health(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_get_health_serviceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'get_health': grpc.unary_unary_rpc_method_handler(
                    servicer.get_health,
                    request_deserializer=cloud__scheduler__sync__bridge__pb2.get_health_request.FromString,
                    response_serializer=cloud__scheduler__sync__bridge__pb2.get_health_response.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'swdv.cloud_scheduler_sync_bridge.get_health_service', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class get_health_service(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def get_health(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/swdv.cloud_scheduler_sync_bridge.get_health_service/get_health',
            cloud__scheduler__sync__bridge__pb2.get_health_request.SerializeToString,
            cloud__scheduler__sync__bridge__pb2.get_health_response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)


class get_vehicle_sync_info_serviceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.get_vehicle_sync_info = channel.unary_unary(
                '/swdv.cloud_scheduler_sync_bridge.get_vehicle_sync_info_service/get_vehicle_sync_info',
                request_serializer=cloud__scheduler__sync__bridge__pb2.get_vehicle_sync_info_request.SerializeToString,
                response_deserializer=cloud__scheduler__sync__bridge__pb2.get_vehicle_sync_info_response.FromString,
                )


class get_vehicle_sync_info_serviceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def get_vehicle_sync_info(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_get_vehicle_sync_info_serviceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'get_vehicle_sync_info': grpc.unary_unary_rpc_method_handler(
                    servicer.get_vehicle_sync_info,
                    request_deserializer=cloud__scheduler__sync__bridge__pb2.get_vehicle_sync_info_request.FromString,
                    response_serializer=cloud__scheduler__sync__bridge__pb2.get_vehicle_sync_info_response.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'swdv.cloud_scheduler_sync_bridge.get_vehicle_sync_info_service', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class get_vehicle_sync_info_service(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def get_vehicle_sync_info(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/swdv.cloud_scheduler_sync_bridge.get_vehicle_sync_info_service/get_vehicle_sync_info',
            cloud__scheduler__sync__bridge__pb2.get_vehicle_sync_info_request.SerializeToString,
            cloud__scheduler__sync__bridge__pb2.get_vehicle_sync_info_response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)


class force_sync_serviceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.force_sync = channel.unary_unary(
                '/swdv.cloud_scheduler_sync_bridge.force_sync_service/force_sync',
                request_serializer=cloud__scheduler__sync__bridge__pb2.force_sync_request.SerializeToString,
                response_deserializer=cloud__scheduler__sync__bridge__pb2.force_sync_response.FromString,
                )


class force_sync_serviceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def force_sync(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_force_sync_serviceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'force_sync': grpc.unary_unary_rpc_method_handler(
                    servicer.force_sync,
                    request_deserializer=cloud__scheduler__sync__bridge__pb2.force_sync_request.FromString,
                    response_serializer=cloud__scheduler__sync__bridge__pb2.force_sync_response.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'swdv.cloud_scheduler_sync_bridge.force_sync_service', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class force_sync_service(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def force_sync(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/swdv.cloud_scheduler_sync_bridge.force_sync_service/force_sync',
            cloud__scheduler__sync__bridge__pb2.force_sync_request.SerializeToString,
            cloud__scheduler__sync__bridge__pb2.force_sync_response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)


class healthy_serviceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.healthy = channel.unary_unary(
                '/swdv.cloud_scheduler_sync_bridge.healthy_service/healthy',
                request_serializer=cloud__scheduler__sync__bridge__pb2.healthy_request.SerializeToString,
                response_deserializer=cloud__scheduler__sync__bridge__pb2.healthy_response.FromString,
                )


class healthy_serviceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def healthy(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_healthy_serviceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'healthy': grpc.unary_unary_rpc_method_handler(
                    servicer.healthy,
                    request_deserializer=cloud__scheduler__sync__bridge__pb2.healthy_request.FromString,
                    response_serializer=cloud__scheduler__sync__bridge__pb2.healthy_response.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'swdv.cloud_scheduler_sync_bridge.healthy_service', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class healthy_service(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def healthy(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/swdv.cloud_scheduler_sync_bridge.healthy_service/healthy',
            cloud__scheduler__sync__bridge__pb2.healthy_request.SerializeToString,
            cloud__scheduler__sync__bridge__pb2.healthy_response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
