# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import cloud_scheduler_service_pb2 as cloud__scheduler__service__pb2


class create_job_serviceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.create_job = channel.unary_unary(
                '/swdv.cloud_scheduler_service.create_job_service/create_job',
                request_serializer=cloud__scheduler__service__pb2.create_job_request.SerializeToString,
                response_deserializer=cloud__scheduler__service__pb2.create_job_response.FromString,
                )


class create_job_serviceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def create_job(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_create_job_serviceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'create_job': grpc.unary_unary_rpc_method_handler(
                    servicer.create_job,
                    request_deserializer=cloud__scheduler__service__pb2.create_job_request.FromString,
                    response_serializer=cloud__scheduler__service__pb2.create_job_response.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'swdv.cloud_scheduler_service.create_job_service', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class create_job_service(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def create_job(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/swdv.cloud_scheduler_service.create_job_service/create_job',
            cloud__scheduler__service__pb2.create_job_request.SerializeToString,
            cloud__scheduler__service__pb2.create_job_response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)


class update_job_serviceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.update_job = channel.unary_unary(
                '/swdv.cloud_scheduler_service.update_job_service/update_job',
                request_serializer=cloud__scheduler__service__pb2.update_job_request.SerializeToString,
                response_deserializer=cloud__scheduler__service__pb2.update_job_response.FromString,
                )


class update_job_serviceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def update_job(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_update_job_serviceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'update_job': grpc.unary_unary_rpc_method_handler(
                    servicer.update_job,
                    request_deserializer=cloud__scheduler__service__pb2.update_job_request.FromString,
                    response_serializer=cloud__scheduler__service__pb2.update_job_response.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'swdv.cloud_scheduler_service.update_job_service', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class update_job_service(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def update_job(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/swdv.cloud_scheduler_service.update_job_service/update_job',
            cloud__scheduler__service__pb2.update_job_request.SerializeToString,
            cloud__scheduler__service__pb2.update_job_response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)


class delete_job_serviceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.delete_job = channel.unary_unary(
                '/swdv.cloud_scheduler_service.delete_job_service/delete_job',
                request_serializer=cloud__scheduler__service__pb2.delete_job_request.SerializeToString,
                response_deserializer=cloud__scheduler__service__pb2.delete_job_response.FromString,
                )


class delete_job_serviceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def delete_job(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_delete_job_serviceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'delete_job': grpc.unary_unary_rpc_method_handler(
                    servicer.delete_job,
                    request_deserializer=cloud__scheduler__service__pb2.delete_job_request.FromString,
                    response_serializer=cloud__scheduler__service__pb2.delete_job_response.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'swdv.cloud_scheduler_service.delete_job_service', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class delete_job_service(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def delete_job(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/swdv.cloud_scheduler_service.delete_job_service/delete_job',
            cloud__scheduler__service__pb2.delete_job_request.SerializeToString,
            cloud__scheduler__service__pb2.delete_job_response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)


class pause_job_serviceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.pause_job = channel.unary_unary(
                '/swdv.cloud_scheduler_service.pause_job_service/pause_job',
                request_serializer=cloud__scheduler__service__pb2.pause_job_request.SerializeToString,
                response_deserializer=cloud__scheduler__service__pb2.pause_job_response.FromString,
                )


class pause_job_serviceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def pause_job(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_pause_job_serviceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'pause_job': grpc.unary_unary_rpc_method_handler(
                    servicer.pause_job,
                    request_deserializer=cloud__scheduler__service__pb2.pause_job_request.FromString,
                    response_serializer=cloud__scheduler__service__pb2.pause_job_response.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'swdv.cloud_scheduler_service.pause_job_service', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class pause_job_service(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def pause_job(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/swdv.cloud_scheduler_service.pause_job_service/pause_job',
            cloud__scheduler__service__pb2.pause_job_request.SerializeToString,
            cloud__scheduler__service__pb2.pause_job_response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)


class resume_job_serviceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.resume_job = channel.unary_unary(
                '/swdv.cloud_scheduler_service.resume_job_service/resume_job',
                request_serializer=cloud__scheduler__service__pb2.resume_job_request.SerializeToString,
                response_deserializer=cloud__scheduler__service__pb2.resume_job_response.FromString,
                )


class resume_job_serviceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def resume_job(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_resume_job_serviceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'resume_job': grpc.unary_unary_rpc_method_handler(
                    servicer.resume_job,
                    request_deserializer=cloud__scheduler__service__pb2.resume_job_request.FromString,
                    response_serializer=cloud__scheduler__service__pb2.resume_job_response.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'swdv.cloud_scheduler_service.resume_job_service', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class resume_job_service(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def resume_job(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/swdv.cloud_scheduler_service.resume_job_service/resume_job',
            cloud__scheduler__service__pb2.resume_job_request.SerializeToString,
            cloud__scheduler__service__pb2.resume_job_response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)


class trigger_job_serviceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.trigger_job = channel.unary_unary(
                '/swdv.cloud_scheduler_service.trigger_job_service/trigger_job',
                request_serializer=cloud__scheduler__service__pb2.trigger_job_request.SerializeToString,
                response_deserializer=cloud__scheduler__service__pb2.trigger_job_response.FromString,
                )


class trigger_job_serviceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def trigger_job(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_trigger_job_serviceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'trigger_job': grpc.unary_unary_rpc_method_handler(
                    servicer.trigger_job,
                    request_deserializer=cloud__scheduler__service__pb2.trigger_job_request.FromString,
                    response_serializer=cloud__scheduler__service__pb2.trigger_job_response.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'swdv.cloud_scheduler_service.trigger_job_service', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class trigger_job_service(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def trigger_job(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/swdv.cloud_scheduler_service.trigger_job_service/trigger_job',
            cloud__scheduler__service__pb2.trigger_job_request.SerializeToString,
            cloud__scheduler__service__pb2.trigger_job_response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)


class get_job_serviceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.get_job = channel.unary_unary(
                '/swdv.cloud_scheduler_service.get_job_service/get_job',
                request_serializer=cloud__scheduler__service__pb2.get_job_request.SerializeToString,
                response_deserializer=cloud__scheduler__service__pb2.get_job_response.FromString,
                )


class get_job_serviceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def get_job(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_get_job_serviceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'get_job': grpc.unary_unary_rpc_method_handler(
                    servicer.get_job,
                    request_deserializer=cloud__scheduler__service__pb2.get_job_request.FromString,
                    response_serializer=cloud__scheduler__service__pb2.get_job_response.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'swdv.cloud_scheduler_service.get_job_service', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class get_job_service(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def get_job(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/swdv.cloud_scheduler_service.get_job_service/get_job',
            cloud__scheduler__service__pb2.get_job_request.SerializeToString,
            cloud__scheduler__service__pb2.get_job_response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)


class list_jobs_serviceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.list_jobs = channel.unary_unary(
                '/swdv.cloud_scheduler_service.list_jobs_service/list_jobs',
                request_serializer=cloud__scheduler__service__pb2.list_jobs_request.SerializeToString,
                response_deserializer=cloud__scheduler__service__pb2.list_jobs_response.FromString,
                )


class list_jobs_serviceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def list_jobs(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_list_jobs_serviceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'list_jobs': grpc.unary_unary_rpc_method_handler(
                    servicer.list_jobs,
                    request_deserializer=cloud__scheduler__service__pb2.list_jobs_request.FromString,
                    response_serializer=cloud__scheduler__service__pb2.list_jobs_response.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'swdv.cloud_scheduler_service.list_jobs_service', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class list_jobs_service(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def list_jobs(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/swdv.cloud_scheduler_service.list_jobs_service/list_jobs',
            cloud__scheduler__service__pb2.list_jobs_request.SerializeToString,
            cloud__scheduler__service__pb2.list_jobs_response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)


class get_job_executions_serviceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.get_job_executions = channel.unary_unary(
                '/swdv.cloud_scheduler_service.get_job_executions_service/get_job_executions',
                request_serializer=cloud__scheduler__service__pb2.get_job_executions_request.SerializeToString,
                response_deserializer=cloud__scheduler__service__pb2.get_job_executions_response.FromString,
                )


class get_job_executions_serviceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def get_job_executions(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_get_job_executions_serviceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'get_job_executions': grpc.unary_unary_rpc_method_handler(
                    servicer.get_job_executions,
                    request_deserializer=cloud__scheduler__service__pb2.get_job_executions_request.FromString,
                    response_serializer=cloud__scheduler__service__pb2.get_job_executions_response.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'swdv.cloud_scheduler_service.get_job_executions_service', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class get_job_executions_service(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def get_job_executions(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/swdv.cloud_scheduler_service.get_job_executions_service/get_job_executions',
            cloud__scheduler__service__pb2.get_job_executions_request.SerializeToString,
            cloud__scheduler__service__pb2.get_job_executions_response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)


class create_fleet_job_serviceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.create_fleet_job = channel.unary_unary(
                '/swdv.cloud_scheduler_service.create_fleet_job_service/create_fleet_job',
                request_serializer=cloud__scheduler__service__pb2.create_fleet_job_request.SerializeToString,
                response_deserializer=cloud__scheduler__service__pb2.create_fleet_job_response.FromString,
                )


class create_fleet_job_serviceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def create_fleet_job(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_create_fleet_job_serviceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'create_fleet_job': grpc.unary_unary_rpc_method_handler(
                    servicer.create_fleet_job,
                    request_deserializer=cloud__scheduler__service__pb2.create_fleet_job_request.FromString,
                    response_serializer=cloud__scheduler__service__pb2.create_fleet_job_response.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'swdv.cloud_scheduler_service.create_fleet_job_service', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class create_fleet_job_service(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def create_fleet_job(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/swdv.cloud_scheduler_service.create_fleet_job_service/create_fleet_job',
            cloud__scheduler__service__pb2.create_fleet_job_request.SerializeToString,
            cloud__scheduler__service__pb2.create_fleet_job_response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)


class delete_fleet_job_serviceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.delete_fleet_job = channel.unary_unary(
                '/swdv.cloud_scheduler_service.delete_fleet_job_service/delete_fleet_job',
                request_serializer=cloud__scheduler__service__pb2.delete_fleet_job_request.SerializeToString,
                response_deserializer=cloud__scheduler__service__pb2.delete_fleet_job_response.FromString,
                )


class delete_fleet_job_serviceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def delete_fleet_job(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_delete_fleet_job_serviceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'delete_fleet_job': grpc.unary_unary_rpc_method_handler(
                    servicer.delete_fleet_job,
                    request_deserializer=cloud__scheduler__service__pb2.delete_fleet_job_request.FromString,
                    response_serializer=cloud__scheduler__service__pb2.delete_fleet_job_response.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'swdv.cloud_scheduler_service.delete_fleet_job_service', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class delete_fleet_job_service(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def delete_fleet_job(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/swdv.cloud_scheduler_service.delete_fleet_job_service/delete_fleet_job',
            cloud__scheduler__service__pb2.delete_fleet_job_request.SerializeToString,
            cloud__scheduler__service__pb2.delete_fleet_job_response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)


class get_fleet_job_stats_serviceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.get_fleet_job_stats = channel.unary_unary(
                '/swdv.cloud_scheduler_service.get_fleet_job_stats_service/get_fleet_job_stats',
                request_serializer=cloud__scheduler__service__pb2.get_fleet_job_stats_request.SerializeToString,
                response_deserializer=cloud__scheduler__service__pb2.get_fleet_job_stats_response.FromString,
                )


class get_fleet_job_stats_serviceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def get_fleet_job_stats(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_get_fleet_job_stats_serviceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'get_fleet_job_stats': grpc.unary_unary_rpc_method_handler(
                    servicer.get_fleet_job_stats,
                    request_deserializer=cloud__scheduler__service__pb2.get_fleet_job_stats_request.FromString,
                    response_serializer=cloud__scheduler__service__pb2.get_fleet_job_stats_response.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'swdv.cloud_scheduler_service.get_fleet_job_stats_service', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class get_fleet_job_stats_service(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def get_fleet_job_stats(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/swdv.cloud_scheduler_service.get_fleet_job_stats_service/get_fleet_job_stats',
            cloud__scheduler__service__pb2.get_fleet_job_stats_request.SerializeToString,
            cloud__scheduler__service__pb2.get_fleet_job_stats_response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)


class healthy_serviceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.healthy = channel.unary_unary(
                '/swdv.cloud_scheduler_service.healthy_service/healthy',
                request_serializer=cloud__scheduler__service__pb2.healthy_request.SerializeToString,
                response_deserializer=cloud__scheduler__service__pb2.healthy_response.FromString,
                )


class healthy_serviceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def healthy(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_healthy_serviceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'healthy': grpc.unary_unary_rpc_method_handler(
                    servicer.healthy,
                    request_deserializer=cloud__scheduler__service__pb2.healthy_request.FromString,
                    response_serializer=cloud__scheduler__service__pb2.healthy_response.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'swdv.cloud_scheduler_service.healthy_service', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class healthy_service(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def healthy(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/swdv.cloud_scheduler_service.healthy_service/healthy',
            cloud__scheduler__service__pb2.healthy_request.SerializeToString,
            cloud__scheduler__service__pb2.healthy_response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)


class get_jobs_for_vehicle_serviceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.get_jobs_for_vehicle = channel.unary_unary(
                '/swdv.cloud_scheduler_service.get_jobs_for_vehicle_service/get_jobs_for_vehicle',
                request_serializer=cloud__scheduler__service__pb2.get_jobs_for_vehicle_request.SerializeToString,
                response_deserializer=cloud__scheduler__service__pb2.get_jobs_for_vehicle_response.FromString,
                )


class get_jobs_for_vehicle_serviceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def get_jobs_for_vehicle(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_get_jobs_for_vehicle_serviceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'get_jobs_for_vehicle': grpc.unary_unary_rpc_method_handler(
                    servicer.get_jobs_for_vehicle,
                    request_deserializer=cloud__scheduler__service__pb2.get_jobs_for_vehicle_request.FromString,
                    response_serializer=cloud__scheduler__service__pb2.get_jobs_for_vehicle_response.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'swdv.cloud_scheduler_service.get_jobs_for_vehicle_service', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class get_jobs_for_vehicle_service(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def get_jobs_for_vehicle(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/swdv.cloud_scheduler_service.get_jobs_for_vehicle_service/get_jobs_for_vehicle',
            cloud__scheduler__service__pb2.get_jobs_for_vehicle_request.SerializeToString,
            cloud__scheduler__service__pb2.get_jobs_for_vehicle_response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)


class upsert_job_serviceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.upsert_job = channel.unary_unary(
                '/swdv.cloud_scheduler_service.upsert_job_service/upsert_job',
                request_serializer=cloud__scheduler__service__pb2.upsert_job_request.SerializeToString,
                response_deserializer=cloud__scheduler__service__pb2.upsert_job_response.FromString,
                )


class upsert_job_serviceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def upsert_job(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_upsert_job_serviceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'upsert_job': grpc.unary_unary_rpc_method_handler(
                    servicer.upsert_job,
                    request_deserializer=cloud__scheduler__service__pb2.upsert_job_request.FromString,
                    response_serializer=cloud__scheduler__service__pb2.upsert_job_response.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'swdv.cloud_scheduler_service.upsert_job_service', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class upsert_job_service(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def upsert_job(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/swdv.cloud_scheduler_service.upsert_job_service/upsert_job',
            cloud__scheduler__service__pb2.upsert_job_request.SerializeToString,
            cloud__scheduler__service__pb2.upsert_job_response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)


class record_execution_serviceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.record_execution = channel.unary_unary(
                '/swdv.cloud_scheduler_service.record_execution_service/record_execution',
                request_serializer=cloud__scheduler__service__pb2.record_execution_request.SerializeToString,
                response_deserializer=cloud__scheduler__service__pb2.record_execution_response.FromString,
                )


class record_execution_serviceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def record_execution(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_record_execution_serviceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'record_execution': grpc.unary_unary_rpc_method_handler(
                    servicer.record_execution,
                    request_deserializer=cloud__scheduler__service__pb2.record_execution_request.FromString,
                    response_serializer=cloud__scheduler__service__pb2.record_execution_response.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'swdv.cloud_scheduler_service.record_execution_service', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class record_execution_service(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def record_execution(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/swdv.cloud_scheduler_service.record_execution_service/record_execution',
            cloud__scheduler__service__pb2.record_execution_request.SerializeToString,
            cloud__scheduler__service__pb2.record_execution_response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)


class get_vehicle_sync_state_serviceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.get_vehicle_sync_state = channel.unary_unary(
                '/swdv.cloud_scheduler_service.get_vehicle_sync_state_service/get_vehicle_sync_state',
                request_serializer=cloud__scheduler__service__pb2.get_vehicle_sync_state_request.SerializeToString,
                response_deserializer=cloud__scheduler__service__pb2.get_vehicle_sync_state_response.FromString,
                )


class get_vehicle_sync_state_serviceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def get_vehicle_sync_state(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_get_vehicle_sync_state_serviceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'get_vehicle_sync_state': grpc.unary_unary_rpc_method_handler(
                    servicer.get_vehicle_sync_state,
                    request_deserializer=cloud__scheduler__service__pb2.get_vehicle_sync_state_request.FromString,
                    response_serializer=cloud__scheduler__service__pb2.get_vehicle_sync_state_response.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'swdv.cloud_scheduler_service.get_vehicle_sync_state_service', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class get_vehicle_sync_state_service(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def get_vehicle_sync_state(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/swdv.cloud_scheduler_service.get_vehicle_sync_state_service/get_vehicle_sync_state',
            cloud__scheduler__service__pb2.get_vehicle_sync_state_request.SerializeToString,
            cloud__scheduler__service__pb2.get_vehicle_sync_state_response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)


class update_vehicle_sync_state_serviceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.update_vehicle_sync_state = channel.unary_unary(
                '/swdv.cloud_scheduler_service.update_vehicle_sync_state_service/update_vehicle_sync_state',
                request_serializer=cloud__scheduler__service__pb2.update_vehicle_sync_state_request.SerializeToString,
                response_deserializer=cloud__scheduler__service__pb2.update_vehicle_sync_state_response.FromString,
                )


class update_vehicle_sync_state_serviceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def update_vehicle_sync_state(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_update_vehicle_sync_state_serviceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'update_vehicle_sync_state': grpc.unary_unary_rpc_method_handler(
                    servicer.update_vehicle_sync_state,
                    request_deserializer=cloud__scheduler__service__pb2.update_vehicle_sync_state_request.FromString,
                    response_serializer=cloud__scheduler__service__pb2.update_vehicle_sync_state_response.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'swdv.cloud_scheduler_service.update_vehicle_sync_state_service', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class update_vehicle_sync_state_service(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def update_vehicle_sync_state(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/swdv.cloud_scheduler_service.update_vehicle_sync_state_service/update_vehicle_sync_state',
            cloud__scheduler__service__pb2.update_vehicle_sync_state_request.SerializeToString,
            cloud__scheduler__service__pb2.update_vehicle_sync_state_response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
