# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import cloud_dispatcher_service_pb2 as cloud__dispatcher__service__pb2


class call_method_serviceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.call_method = channel.unary_unary(
                '/swdv.cloud_dispatcher_service.call_method_service/call_method',
                request_serializer=cloud__dispatcher__service__pb2.call_method_request.SerializeToString,
                response_deserializer=cloud__dispatcher__service__pb2.call_method_response.FromString,
                )


class call_method_serviceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def call_method(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_call_method_serviceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'call_method': grpc.unary_unary_rpc_method_handler(
                    servicer.call_method,
                    request_deserializer=cloud__dispatcher__service__pb2.call_method_request.FromString,
                    response_serializer=cloud__dispatcher__service__pb2.call_method_response.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'swdv.cloud_dispatcher_service.call_method_service', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class call_method_service(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def call_method(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/swdv.cloud_dispatcher_service.call_method_service/call_method',
            cloud__dispatcher__service__pb2.call_method_request.SerializeToString,
            cloud__dispatcher__service__pb2.call_method_response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)


class call_method_async_serviceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.call_method_async = channel.unary_unary(
                '/swdv.cloud_dispatcher_service.call_method_async_service/call_method_async',
                request_serializer=cloud__dispatcher__service__pb2.call_method_async_request.SerializeToString,
                response_deserializer=cloud__dispatcher__service__pb2.call_method_async_response.FromString,
                )


class call_method_async_serviceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def call_method_async(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_call_method_async_serviceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'call_method_async': grpc.unary_unary_rpc_method_handler(
                    servicer.call_method_async,
                    request_deserializer=cloud__dispatcher__service__pb2.call_method_async_request.FromString,
                    response_serializer=cloud__dispatcher__service__pb2.call_method_async_response.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'swdv.cloud_dispatcher_service.call_method_async_service', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class call_method_async_service(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def call_method_async(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/swdv.cloud_dispatcher_service.call_method_async_service/call_method_async',
            cloud__dispatcher__service__pb2.call_method_async_request.SerializeToString,
            cloud__dispatcher__service__pb2.call_method_async_response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)


class get_call_result_serviceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.get_call_result = channel.unary_unary(
                '/swdv.cloud_dispatcher_service.get_call_result_service/get_call_result',
                request_serializer=cloud__dispatcher__service__pb2.get_call_result_request.SerializeToString,
                response_deserializer=cloud__dispatcher__service__pb2.get_call_result_response.FromString,
                )


class get_call_result_serviceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def get_call_result(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_get_call_result_serviceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'get_call_result': grpc.unary_unary_rpc_method_handler(
                    servicer.get_call_result,
                    request_deserializer=cloud__dispatcher__service__pb2.get_call_result_request.FromString,
                    response_serializer=cloud__dispatcher__service__pb2.get_call_result_response.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'swdv.cloud_dispatcher_service.get_call_result_service', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class get_call_result_service(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def get_call_result(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/swdv.cloud_dispatcher_service.get_call_result_service/get_call_result',
            cloud__dispatcher__service__pb2.get_call_result_request.SerializeToString,
            cloud__dispatcher__service__pb2.get_call_result_response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)


class list_pending_calls_serviceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.list_pending_calls = channel.unary_unary(
                '/swdv.cloud_dispatcher_service.list_pending_calls_service/list_pending_calls',
                request_serializer=cloud__dispatcher__service__pb2.list_pending_calls_request.SerializeToString,
                response_deserializer=cloud__dispatcher__service__pb2.list_pending_calls_response.FromString,
                )


class list_pending_calls_serviceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def list_pending_calls(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_list_pending_calls_serviceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'list_pending_calls': grpc.unary_unary_rpc_method_handler(
                    servicer.list_pending_calls,
                    request_deserializer=cloud__dispatcher__service__pb2.list_pending_calls_request.FromString,
                    response_serializer=cloud__dispatcher__service__pb2.list_pending_calls_response.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'swdv.cloud_dispatcher_service.list_pending_calls_service', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class list_pending_calls_service(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def list_pending_calls(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/swdv.cloud_dispatcher_service.list_pending_calls_service/list_pending_calls',
            cloud__dispatcher__service__pb2.list_pending_calls_request.SerializeToString,
            cloud__dispatcher__service__pb2.list_pending_calls_response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)


class cancel_call_serviceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.cancel_call = channel.unary_unary(
                '/swdv.cloud_dispatcher_service.cancel_call_service/cancel_call',
                request_serializer=cloud__dispatcher__service__pb2.cancel_call_request.SerializeToString,
                response_deserializer=cloud__dispatcher__service__pb2.cancel_call_response.FromString,
                )


class cancel_call_serviceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def cancel_call(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_cancel_call_serviceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'cancel_call': grpc.unary_unary_rpc_method_handler(
                    servicer.cancel_call,
                    request_deserializer=cloud__dispatcher__service__pb2.cancel_call_request.FromString,
                    response_serializer=cloud__dispatcher__service__pb2.cancel_call_response.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'swdv.cloud_dispatcher_service.cancel_call_service', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class cancel_call_service(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def cancel_call(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/swdv.cloud_dispatcher_service.cancel_call_service/cancel_call',
            cloud__dispatcher__service__pb2.cancel_call_request.SerializeToString,
            cloud__dispatcher__service__pb2.cancel_call_response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)


class healthy_serviceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.healthy = channel.unary_unary(
                '/swdv.cloud_dispatcher_service.healthy_service/healthy',
                request_serializer=cloud__dispatcher__service__pb2.healthy_request.SerializeToString,
                response_deserializer=cloud__dispatcher__service__pb2.healthy_response.FromString,
                )


class healthy_serviceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def healthy(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_healthy_serviceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'healthy': grpc.unary_unary_rpc_method_handler(
                    servicer.healthy,
                    request_deserializer=cloud__dispatcher__service__pb2.healthy_request.FromString,
                    response_serializer=cloud__dispatcher__service__pb2.healthy_response.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'swdv.cloud_dispatcher_service.healthy_service', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class healthy_service(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def healthy(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/swdv.cloud_dispatcher_service.healthy_service/healthy',
            cloud__dispatcher__service__pb2.healthy_request.SerializeToString,
            cloud__dispatcher__service__pb2.healthy_response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)


class on_call_result_serviceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.subscribe = channel.unary_stream(
                '/swdv.cloud_dispatcher_service.on_call_result_service/subscribe',
                request_serializer=cloud__dispatcher__service__pb2.on_call_result_subscribe_request.SerializeToString,
                response_deserializer=cloud__dispatcher__service__pb2.on_call_result.FromString,
                )


class on_call_result_serviceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def subscribe(self, request, context):
        """Server-streaming RPC for event subscription
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_on_call_result_serviceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'subscribe': grpc.unary_stream_rpc_method_handler(
                    servicer.subscribe,
                    request_deserializer=cloud__dispatcher__service__pb2.on_call_result_subscribe_request.FromString,
                    response_serializer=cloud__dispatcher__service__pb2.on_call_result.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'swdv.cloud_dispatcher_service.on_call_result_service', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class on_call_result_service(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def subscribe(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/swdv.cloud_dispatcher_service.on_call_result_service/subscribe',
            cloud__dispatcher__service__pb2.on_call_result_subscribe_request.SerializeToString,
            cloud__dispatcher__service__pb2.on_call_result.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
