# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import test_types_service_pb2 as test__types__service__pb2


class test_primitives_serviceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.test_primitives = channel.unary_unary(
                '/swdv.test_types_service.test_primitives_service/test_primitives',
                request_serializer=test__types__service__pb2.test_primitives_request.SerializeToString,
                response_deserializer=test__types__service__pb2.test_primitives_response.FromString,
                )


class test_primitives_serviceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def test_primitives(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_test_primitives_serviceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'test_primitives': grpc.unary_unary_rpc_method_handler(
                    servicer.test_primitives,
                    request_deserializer=test__types__service__pb2.test_primitives_request.FromString,
                    response_serializer=test__types__service__pb2.test_primitives_response.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'swdv.test_types_service.test_primitives_service', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class test_primitives_service(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def test_primitives(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/swdv.test_types_service.test_primitives_service/test_primitives',
            test__types__service__pb2.test_primitives_request.SerializeToString,
            test__types__service__pb2.test_primitives_response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)


class test_arrays_serviceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.test_arrays = channel.unary_unary(
                '/swdv.test_types_service.test_arrays_service/test_arrays',
                request_serializer=test__types__service__pb2.test_arrays_request.SerializeToString,
                response_deserializer=test__types__service__pb2.test_arrays_response.FromString,
                )


class test_arrays_serviceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def test_arrays(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_test_arrays_serviceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'test_arrays': grpc.unary_unary_rpc_method_handler(
                    servicer.test_arrays,
                    request_deserializer=test__types__service__pb2.test_arrays_request.FromString,
                    response_serializer=test__types__service__pb2.test_arrays_response.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'swdv.test_types_service.test_arrays_service', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class test_arrays_service(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def test_arrays(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/swdv.test_types_service.test_arrays_service/test_arrays',
            test__types__service__pb2.test_arrays_request.SerializeToString,
            test__types__service__pb2.test_arrays_response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)


class test_enums_serviceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.test_enums = channel.unary_unary(
                '/swdv.test_types_service.test_enums_service/test_enums',
                request_serializer=test__types__service__pb2.test_enums_request.SerializeToString,
                response_deserializer=test__types__service__pb2.test_enums_response.FromString,
                )


class test_enums_serviceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def test_enums(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_test_enums_serviceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'test_enums': grpc.unary_unary_rpc_method_handler(
                    servicer.test_enums,
                    request_deserializer=test__types__service__pb2.test_enums_request.FromString,
                    response_serializer=test__types__service__pb2.test_enums_response.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'swdv.test_types_service.test_enums_service', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class test_enums_service(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def test_enums(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/swdv.test_types_service.test_enums_service/test_enums',
            test__types__service__pb2.test_enums_request.SerializeToString,
            test__types__service__pb2.test_enums_response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)


class test_nested_structs_serviceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.test_nested_structs = channel.unary_unary(
                '/swdv.test_types_service.test_nested_structs_service/test_nested_structs',
                request_serializer=test__types__service__pb2.test_nested_structs_request.SerializeToString,
                response_deserializer=test__types__service__pb2.test_nested_structs_response.FromString,
                )


class test_nested_structs_serviceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def test_nested_structs(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_test_nested_structs_serviceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'test_nested_structs': grpc.unary_unary_rpc_method_handler(
                    servicer.test_nested_structs,
                    request_deserializer=test__types__service__pb2.test_nested_structs_request.FromString,
                    response_serializer=test__types__service__pb2.test_nested_structs_response.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'swdv.test_types_service.test_nested_structs_service', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class test_nested_structs_service(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def test_nested_structs(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/swdv.test_types_service.test_nested_structs_service/test_nested_structs',
            test__types__service__pb2.test_nested_structs_request.SerializeToString,
            test__types__service__pb2.test_nested_structs_response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)


class test_optional_fields_serviceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.test_optional_fields = channel.unary_unary(
                '/swdv.test_types_service.test_optional_fields_service/test_optional_fields',
                request_serializer=test__types__service__pb2.test_optional_fields_request.SerializeToString,
                response_deserializer=test__types__service__pb2.test_optional_fields_response.FromString,
                )


class test_optional_fields_serviceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def test_optional_fields(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_test_optional_fields_serviceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'test_optional_fields': grpc.unary_unary_rpc_method_handler(
                    servicer.test_optional_fields,
                    request_deserializer=test__types__service__pb2.test_optional_fields_request.FromString,
                    response_serializer=test__types__service__pb2.test_optional_fields_response.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'swdv.test_types_service.test_optional_fields_service', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class test_optional_fields_service(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def test_optional_fields(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/swdv.test_types_service.test_optional_fields_service/test_optional_fields',
            test__types__service__pb2.test_optional_fields_request.SerializeToString,
            test__types__service__pb2.test_optional_fields_response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)


class test_sensor_data_stream_serviceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.test_sensor_data_stream = channel.unary_unary(
                '/swdv.test_types_service.test_sensor_data_stream_service/test_sensor_data_stream',
                request_serializer=test__types__service__pb2.test_sensor_data_stream_request.SerializeToString,
                response_deserializer=test__types__service__pb2.test_sensor_data_stream_response.FromString,
                )


class test_sensor_data_stream_serviceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def test_sensor_data_stream(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_test_sensor_data_stream_serviceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'test_sensor_data_stream': grpc.unary_unary_rpc_method_handler(
                    servicer.test_sensor_data_stream,
                    request_deserializer=test__types__service__pb2.test_sensor_data_stream_request.FromString,
                    response_serializer=test__types__service__pb2.test_sensor_data_stream_response.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'swdv.test_types_service.test_sensor_data_stream_service', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class test_sensor_data_stream_service(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def test_sensor_data_stream(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/swdv.test_types_service.test_sensor_data_stream_service/test_sensor_data_stream',
            test__types__service__pb2.test_sensor_data_stream_request.SerializeToString,
            test__types__service__pb2.test_sensor_data_stream_response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
