# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import backend_transport_service_pb2 as backend__transport__service__pb2


class publish_serviceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.publish = channel.unary_unary(
                '/swdv.backend_transport_service.publish_service/publish',
                request_serializer=backend__transport__service__pb2.publish_request.SerializeToString,
                response_deserializer=backend__transport__service__pb2.publish_response.FromString,
                )


class publish_serviceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def publish(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_publish_serviceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'publish': grpc.unary_unary_rpc_method_handler(
                    servicer.publish,
                    request_deserializer=backend__transport__service__pb2.publish_request.FromString,
                    response_serializer=backend__transport__service__pb2.publish_response.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'swdv.backend_transport_service.publish_service', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class publish_service(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def publish(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/swdv.backend_transport_service.publish_service/publish',
            backend__transport__service__pb2.publish_request.SerializeToString,
            backend__transport__service__pb2.publish_response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)


class get_connection_status_serviceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.get_connection_status = channel.unary_unary(
                '/swdv.backend_transport_service.get_connection_status_service/get_connection_status',
                request_serializer=backend__transport__service__pb2.get_connection_status_request.SerializeToString,
                response_deserializer=backend__transport__service__pb2.get_connection_status_response.FromString,
                )


class get_connection_status_serviceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def get_connection_status(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_get_connection_status_serviceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'get_connection_status': grpc.unary_unary_rpc_method_handler(
                    servicer.get_connection_status,
                    request_deserializer=backend__transport__service__pb2.get_connection_status_request.FromString,
                    response_serializer=backend__transport__service__pb2.get_connection_status_response.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'swdv.backend_transport_service.get_connection_status_service', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class get_connection_status_service(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def get_connection_status(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/swdv.backend_transport_service.get_connection_status_service/get_connection_status',
            backend__transport__service__pb2.get_connection_status_request.SerializeToString,
            backend__transport__service__pb2.get_connection_status_response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)


class get_queue_status_serviceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.get_queue_status = channel.unary_unary(
                '/swdv.backend_transport_service.get_queue_status_service/get_queue_status',
                request_serializer=backend__transport__service__pb2.get_queue_status_request.SerializeToString,
                response_deserializer=backend__transport__service__pb2.get_queue_status_response.FromString,
                )


class get_queue_status_serviceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def get_queue_status(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_get_queue_status_serviceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'get_queue_status': grpc.unary_unary_rpc_method_handler(
                    servicer.get_queue_status,
                    request_deserializer=backend__transport__service__pb2.get_queue_status_request.FromString,
                    response_serializer=backend__transport__service__pb2.get_queue_status_response.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'swdv.backend_transport_service.get_queue_status_service', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class get_queue_status_service(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def get_queue_status(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/swdv.backend_transport_service.get_queue_status_service/get_queue_status',
            backend__transport__service__pb2.get_queue_status_request.SerializeToString,
            backend__transport__service__pb2.get_queue_status_response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)


class get_stats_serviceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.get_stats = channel.unary_unary(
                '/swdv.backend_transport_service.get_stats_service/get_stats',
                request_serializer=backend__transport__service__pb2.get_stats_request.SerializeToString,
                response_deserializer=backend__transport__service__pb2.get_stats_response.FromString,
                )


class get_stats_serviceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def get_stats(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_get_stats_serviceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'get_stats': grpc.unary_unary_rpc_method_handler(
                    servicer.get_stats,
                    request_deserializer=backend__transport__service__pb2.get_stats_request.FromString,
                    response_serializer=backend__transport__service__pb2.get_stats_response.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'swdv.backend_transport_service.get_stats_service', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class get_stats_service(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def get_stats(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/swdv.backend_transport_service.get_stats_service/get_stats',
            backend__transport__service__pb2.get_stats_request.SerializeToString,
            backend__transport__service__pb2.get_stats_response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)


class healthy_serviceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.healthy = channel.unary_unary(
                '/swdv.backend_transport_service.healthy_service/healthy',
                request_serializer=backend__transport__service__pb2.healthy_request.SerializeToString,
                response_deserializer=backend__transport__service__pb2.healthy_response.FromString,
                )


class healthy_serviceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def healthy(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_healthy_serviceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'healthy': grpc.unary_unary_rpc_method_handler(
                    servicer.healthy,
                    request_deserializer=backend__transport__service__pb2.healthy_request.FromString,
                    response_serializer=backend__transport__service__pb2.healthy_response.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'swdv.backend_transport_service.healthy_service', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class healthy_service(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def healthy(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/swdv.backend_transport_service.healthy_service/healthy',
            backend__transport__service__pb2.healthy_request.SerializeToString,
            backend__transport__service__pb2.healthy_response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)


class get_content_id_serviceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.get_content_id = channel.unary_unary(
                '/swdv.backend_transport_service.get_content_id_service/get_content_id',
                request_serializer=backend__transport__service__pb2.get_content_id_request.SerializeToString,
                response_deserializer=backend__transport__service__pb2.get_content_id_response.FromString,
                )


class get_content_id_serviceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def get_content_id(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_get_content_id_serviceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'get_content_id': grpc.unary_unary_rpc_method_handler(
                    servicer.get_content_id,
                    request_deserializer=backend__transport__service__pb2.get_content_id_request.FromString,
                    response_serializer=backend__transport__service__pb2.get_content_id_response.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'swdv.backend_transport_service.get_content_id_service', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class get_content_id_service(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def get_content_id(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/swdv.backend_transport_service.get_content_id_service/get_content_id',
            backend__transport__service__pb2.get_content_id_request.SerializeToString,
            backend__transport__service__pb2.get_content_id_response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)


class on_content_serviceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.subscribe = channel.unary_stream(
                '/swdv.backend_transport_service.on_content_service/subscribe',
                request_serializer=backend__transport__service__pb2.on_content_subscribe_request.SerializeToString,
                response_deserializer=backend__transport__service__pb2.on_content.FromString,
                )


class on_content_serviceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def subscribe(self, request, context):
        """Server-streaming RPC for event subscription
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_on_content_serviceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'subscribe': grpc.unary_stream_rpc_method_handler(
                    servicer.subscribe,
                    request_deserializer=backend__transport__service__pb2.on_content_subscribe_request.FromString,
                    response_serializer=backend__transport__service__pb2.on_content.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'swdv.backend_transport_service.on_content_service', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class on_content_service(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def subscribe(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/swdv.backend_transport_service.on_content_service/subscribe',
            backend__transport__service__pb2.on_content_subscribe_request.SerializeToString,
            backend__transport__service__pb2.on_content.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)


class on_ack_serviceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.subscribe = channel.unary_stream(
                '/swdv.backend_transport_service.on_ack_service/subscribe',
                request_serializer=backend__transport__service__pb2.on_ack_subscribe_request.SerializeToString,
                response_deserializer=backend__transport__service__pb2.on_ack.FromString,
                )


class on_ack_serviceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def subscribe(self, request, context):
        """Server-streaming RPC for event subscription
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_on_ack_serviceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'subscribe': grpc.unary_stream_rpc_method_handler(
                    servicer.subscribe,
                    request_deserializer=backend__transport__service__pb2.on_ack_subscribe_request.FromString,
                    response_serializer=backend__transport__service__pb2.on_ack.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'swdv.backend_transport_service.on_ack_service', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class on_ack_service(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def subscribe(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/swdv.backend_transport_service.on_ack_service/subscribe',
            backend__transport__service__pb2.on_ack_subscribe_request.SerializeToString,
            backend__transport__service__pb2.on_ack.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)


class on_connection_changed_serviceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.subscribe = channel.unary_stream(
                '/swdv.backend_transport_service.on_connection_changed_service/subscribe',
                request_serializer=backend__transport__service__pb2.on_connection_changed_subscribe_request.SerializeToString,
                response_deserializer=backend__transport__service__pb2.on_connection_changed.FromString,
                )


class on_connection_changed_serviceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def subscribe(self, request, context):
        """Server-streaming RPC for event subscription
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_on_connection_changed_serviceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'subscribe': grpc.unary_stream_rpc_method_handler(
                    servicer.subscribe,
                    request_deserializer=backend__transport__service__pb2.on_connection_changed_subscribe_request.FromString,
                    response_serializer=backend__transport__service__pb2.on_connection_changed.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'swdv.backend_transport_service.on_connection_changed_service', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class on_connection_changed_service(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def subscribe(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/swdv.backend_transport_service.on_connection_changed_service/subscribe',
            backend__transport__service__pb2.on_connection_changed_subscribe_request.SerializeToString,
            backend__transport__service__pb2.on_connection_changed.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)


class on_queue_status_changed_serviceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.subscribe = channel.unary_stream(
                '/swdv.backend_transport_service.on_queue_status_changed_service/subscribe',
                request_serializer=backend__transport__service__pb2.on_queue_status_changed_subscribe_request.SerializeToString,
                response_deserializer=backend__transport__service__pb2.on_queue_status_changed.FromString,
                )


class on_queue_status_changed_serviceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def subscribe(self, request, context):
        """Server-streaming RPC for event subscription
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_on_queue_status_changed_serviceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'subscribe': grpc.unary_stream_rpc_method_handler(
                    servicer.subscribe,
                    request_deserializer=backend__transport__service__pb2.on_queue_status_changed_subscribe_request.FromString,
                    response_serializer=backend__transport__service__pb2.on_queue_status_changed.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'swdv.backend_transport_service.on_queue_status_changed_service', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class on_queue_status_changed_service(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def subscribe(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/swdv.backend_transport_service.on_queue_status_changed_service/subscribe',
            backend__transport__service__pb2.on_queue_status_changed_subscribe_request.SerializeToString,
            backend__transport__service__pb2.on_queue_status_changed.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
