# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: dispatcher-service.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18\x64ispatcher-service.proto\x12\x14swdv.ifex_dispatcher\"b\n\rmethod_call_t\x12\x14\n\x0cservice_name\x18\x01 \x01(\t\x12\x13\n\x0bmethod_name\x18\x02 \x01(\t\x12\x12\n\nparameters\x18\x03 \x01(\t\x12\x12\n\ntimeout_ms\x18\x04 \x01(\r\"\x9c\x01\n\rcall_result_t\x12\x33\n\x06status\x18\x01 \x01(\x0e\x32#.swdv.ifex_dispatcher.call_status_t\x12\x10\n\x08response\x18\x02 \x01(\t\x12\x15\n\rerror_message\x18\x03 \x01(\t\x12\x13\n\x0b\x64uration_ms\x18\x04 \x01(\r\x12\x18\n\x10service_endpoint\x18\x05 \x01(\t\"H\n\x13\x63\x61ll_method_request\x12\x31\n\x04\x63\x61ll\x18\x01 \x01(\x0b\x32#.swdv.ifex_dispatcher.method_call_t\"K\n\x14\x63\x61ll_method_response\x12\x33\n\x06result\x18\x01 \x01(\x0b\x32#.swdv.ifex_dispatcher.call_result_t*|\n\rcall_status_t\x12\x0b\n\x07SUCCESS\x10\x00\x12\n\n\x06\x46\x41ILED\x10\x01\x12\x0b\n\x07TIMEOUT\x10\x02\x12\x17\n\x13SERVICE_UNAVAILABLE\x10\x03\x12\x14\n\x10METHOD_NOT_FOUND\x10\x04\x12\x16\n\x12INVALID_PARAMETERS\x10\x05\x32{\n\x13\x63\x61ll_method_service\x12\x64\n\x0b\x63\x61ll_method\x12).swdv.ifex_dispatcher.call_method_request\x1a*.swdv.ifex_dispatcher.call_method_responseb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'dispatcher_service_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _CALL_STATUS_T._serialized_start=460
  _CALL_STATUS_T._serialized_end=584
  _METHOD_CALL_T._serialized_start=50
  _METHOD_CALL_T._serialized_end=148
  _CALL_RESULT_T._serialized_start=151
  _CALL_RESULT_T._serialized_end=307
  _CALL_METHOD_REQUEST._serialized_start=309
  _CALL_METHOD_REQUEST._serialized_end=381
  _CALL_METHOD_RESPONSE._serialized_start=383
  _CALL_METHOD_RESPONSE._serialized_end=458
  _CALL_METHOD_SERVICE._serialized_start=586
  _CALL_METHOD_SERVICE._serialized_end=709
# @@protoc_insertion_point(module_scope)
