# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import ifex_dispatcher_service_pb2 as ifex__dispatcher__service__pb2


class call_method_serviceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.call_method = channel.unary_unary(
                '/swdv.ifex_dispatcher.call_method_service/call_method',
                request_serializer=ifex__dispatcher__service__pb2.call_method_request.SerializeToString,
                response_deserializer=ifex__dispatcher__service__pb2.call_method_response.FromString,
                )


class call_method_serviceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def call_method(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_call_method_serviceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'call_method': grpc.unary_unary_rpc_method_handler(
                    servicer.call_method,
                    request_deserializer=ifex__dispatcher__service__pb2.call_method_request.FromString,
                    response_serializer=ifex__dispatcher__service__pb2.call_method_response.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'swdv.ifex_dispatcher.call_method_service', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class call_method_service(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def call_method(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/swdv.ifex_dispatcher.call_method_service/call_method',
            ifex__dispatcher__service__pb2.call_method_request.SerializeToString,
            ifex__dispatcher__service__pb2.call_method_response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
