# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import scheduler_service_pb2 as scheduler__service__pb2


class create_job_serviceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.create_job = channel.unary_unary(
                '/swdv.ifex_scheduler.create_job_service/create_job',
                request_serializer=scheduler__service__pb2.create_job_request.SerializeToString,
                response_deserializer=scheduler__service__pb2.create_job_response.FromString,
                )


class create_job_serviceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def create_job(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_create_job_serviceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'create_job': grpc.unary_unary_rpc_method_handler(
                    servicer.create_job,
                    request_deserializer=scheduler__service__pb2.create_job_request.FromString,
                    response_serializer=scheduler__service__pb2.create_job_response.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'swdv.ifex_scheduler.create_job_service', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class create_job_service(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def create_job(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/swdv.ifex_scheduler.create_job_service/create_job',
            scheduler__service__pb2.create_job_request.SerializeToString,
            scheduler__service__pb2.create_job_response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)


class get_jobs_serviceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.get_jobs = channel.unary_unary(
                '/swdv.ifex_scheduler.get_jobs_service/get_jobs',
                request_serializer=scheduler__service__pb2.get_jobs_request.SerializeToString,
                response_deserializer=scheduler__service__pb2.get_jobs_response.FromString,
                )


class get_jobs_serviceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def get_jobs(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_get_jobs_serviceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'get_jobs': grpc.unary_unary_rpc_method_handler(
                    servicer.get_jobs,
                    request_deserializer=scheduler__service__pb2.get_jobs_request.FromString,
                    response_serializer=scheduler__service__pb2.get_jobs_response.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'swdv.ifex_scheduler.get_jobs_service', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class get_jobs_service(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def get_jobs(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/swdv.ifex_scheduler.get_jobs_service/get_jobs',
            scheduler__service__pb2.get_jobs_request.SerializeToString,
            scheduler__service__pb2.get_jobs_response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)


class get_job_serviceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.get_job = channel.unary_unary(
                '/swdv.ifex_scheduler.get_job_service/get_job',
                request_serializer=scheduler__service__pb2.get_job_request.SerializeToString,
                response_deserializer=scheduler__service__pb2.get_job_response.FromString,
                )


class get_job_serviceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def get_job(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_get_job_serviceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'get_job': grpc.unary_unary_rpc_method_handler(
                    servicer.get_job,
                    request_deserializer=scheduler__service__pb2.get_job_request.FromString,
                    response_serializer=scheduler__service__pb2.get_job_response.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'swdv.ifex_scheduler.get_job_service', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class get_job_service(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def get_job(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/swdv.ifex_scheduler.get_job_service/get_job',
            scheduler__service__pb2.get_job_request.SerializeToString,
            scheduler__service__pb2.get_job_response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)


class update_job_serviceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.update_job = channel.unary_unary(
                '/swdv.ifex_scheduler.update_job_service/update_job',
                request_serializer=scheduler__service__pb2.update_job_request.SerializeToString,
                response_deserializer=scheduler__service__pb2.update_job_response.FromString,
                )


class update_job_serviceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def update_job(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_update_job_serviceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'update_job': grpc.unary_unary_rpc_method_handler(
                    servicer.update_job,
                    request_deserializer=scheduler__service__pb2.update_job_request.FromString,
                    response_serializer=scheduler__service__pb2.update_job_response.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'swdv.ifex_scheduler.update_job_service', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class update_job_service(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def update_job(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/swdv.ifex_scheduler.update_job_service/update_job',
            scheduler__service__pb2.update_job_request.SerializeToString,
            scheduler__service__pb2.update_job_response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)


class delete_job_serviceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.delete_job = channel.unary_unary(
                '/swdv.ifex_scheduler.delete_job_service/delete_job',
                request_serializer=scheduler__service__pb2.delete_job_request.SerializeToString,
                response_deserializer=scheduler__service__pb2.delete_job_response.FromString,
                )


class delete_job_serviceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def delete_job(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_delete_job_serviceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'delete_job': grpc.unary_unary_rpc_method_handler(
                    servicer.delete_job,
                    request_deserializer=scheduler__service__pb2.delete_job_request.FromString,
                    response_serializer=scheduler__service__pb2.delete_job_response.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'swdv.ifex_scheduler.delete_job_service', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class delete_job_service(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def delete_job(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/swdv.ifex_scheduler.delete_job_service/delete_job',
            scheduler__service__pb2.delete_job_request.SerializeToString,
            scheduler__service__pb2.delete_job_response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)


class pause_job_serviceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.pause_job = channel.unary_unary(
                '/swdv.ifex_scheduler.pause_job_service/pause_job',
                request_serializer=scheduler__service__pb2.pause_job_request.SerializeToString,
                response_deserializer=scheduler__service__pb2.pause_job_response.FromString,
                )


class pause_job_serviceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def pause_job(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_pause_job_serviceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'pause_job': grpc.unary_unary_rpc_method_handler(
                    servicer.pause_job,
                    request_deserializer=scheduler__service__pb2.pause_job_request.FromString,
                    response_serializer=scheduler__service__pb2.pause_job_response.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'swdv.ifex_scheduler.pause_job_service', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class pause_job_service(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def pause_job(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/swdv.ifex_scheduler.pause_job_service/pause_job',
            scheduler__service__pb2.pause_job_request.SerializeToString,
            scheduler__service__pb2.pause_job_response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)


class resume_job_serviceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.resume_job = channel.unary_unary(
                '/swdv.ifex_scheduler.resume_job_service/resume_job',
                request_serializer=scheduler__service__pb2.resume_job_request.SerializeToString,
                response_deserializer=scheduler__service__pb2.resume_job_response.FromString,
                )


class resume_job_serviceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def resume_job(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_resume_job_serviceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'resume_job': grpc.unary_unary_rpc_method_handler(
                    servicer.resume_job,
                    request_deserializer=scheduler__service__pb2.resume_job_request.FromString,
                    response_serializer=scheduler__service__pb2.resume_job_response.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'swdv.ifex_scheduler.resume_job_service', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class resume_job_service(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def resume_job(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/swdv.ifex_scheduler.resume_job_service/resume_job',
            scheduler__service__pb2.resume_job_request.SerializeToString,
            scheduler__service__pb2.resume_job_response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)


class trigger_job_serviceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.trigger_job = channel.unary_unary(
                '/swdv.ifex_scheduler.trigger_job_service/trigger_job',
                request_serializer=scheduler__service__pb2.trigger_job_request.SerializeToString,
                response_deserializer=scheduler__service__pb2.trigger_job_response.FromString,
                )


class trigger_job_serviceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def trigger_job(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_trigger_job_serviceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'trigger_job': grpc.unary_unary_rpc_method_handler(
                    servicer.trigger_job,
                    request_deserializer=scheduler__service__pb2.trigger_job_request.FromString,
                    response_serializer=scheduler__service__pb2.trigger_job_response.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'swdv.ifex_scheduler.trigger_job_service', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class trigger_job_service(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def trigger_job(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/swdv.ifex_scheduler.trigger_job_service/trigger_job',
            scheduler__service__pb2.trigger_job_request.SerializeToString,
            scheduler__service__pb2.trigger_job_response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)


class get_calendar_view_serviceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.get_calendar_view = channel.unary_unary(
                '/swdv.ifex_scheduler.get_calendar_view_service/get_calendar_view',
                request_serializer=scheduler__service__pb2.get_calendar_view_request.SerializeToString,
                response_deserializer=scheduler__service__pb2.get_calendar_view_response.FromString,
                )


class get_calendar_view_serviceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def get_calendar_view(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_get_calendar_view_serviceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'get_calendar_view': grpc.unary_unary_rpc_method_handler(
                    servicer.get_calendar_view,
                    request_deserializer=scheduler__service__pb2.get_calendar_view_request.FromString,
                    response_serializer=scheduler__service__pb2.get_calendar_view_response.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'swdv.ifex_scheduler.get_calendar_view_service', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class get_calendar_view_service(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def get_calendar_view(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/swdv.ifex_scheduler.get_calendar_view_service/get_calendar_view',
            scheduler__service__pb2.get_calendar_view_request.SerializeToString,
            scheduler__service__pb2.get_calendar_view_response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
